# No need to set modifyImagesWithDigest to `true` - this is the default
# behavior
signatures:
  - image: "ghcr.io/kubewarden/tests/pod-privileged:v0.2.1"
    certificates:
      # user-1
      - |
        -----BEGIN CERTIFICATE-----
        MIIFADCCAuigAwIBAgIUGrWB8MUm/TCZEF3snMUB6ojIWJEwDQYJKoZIhvcNAQEL
        BQAwfDELMAkGA1UEBhMCVVMxDjAMBgNVBAgMBVN0YXRlMQ0wCwYDVQQHDARDaXR5
        MRUwEwYDVQQKDAxPcmdhbml6YXRpb24xHDAaBgNVBAsME09yZ2FuaXphdGlvbmFs
        IFVuaXQxGTAXBgNVBAMMEE15SW50ZXJtZWRpYXRlQ0EwHhcNMjUxMDAxMTIyNTEx
        WhcNMzUwOTI5MTIyNTExWjB6MQswCQYDVQQGEwJVUzEOMAwGA1UECAwFU3RhdGUx
        DTALBgNVBAcMBENpdHkxFTATBgNVBAoMDE9yZ2FuaXphdGlvbjEcMBoGA1UECwwT
        T3JnYW5pemF0aW9uYWwgVW5pdDEXMBUGA1UEAwwObXkuZXhhbXBsZS5jb20wggEi
        MA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCZh84ef2f3w1F2pRsLrgeKtGO1
        wRHT0UAHadPMIBQVv5LI+PgS3m3hUVXXPprFEv94OE8EysAMklLYxOxTElVJUq0S
        Wy/EP098VHz10e9lcpmDflQ07io+0ORYwYiiTZ6cLNI1Avt583rNwYQR1L4gkCUt
        P+QtO8G4apWQSvj06auxd0iPJbyJSq3uAfMAhhBX4dKVjgw+zbxvz93HoQtNu0Eg
        /sV90YegchW1XP/iDLe3HumX8SOP0eIbVluiSqIZk+0KXBHhXaUbAj8OGqViQNe6
        uk05tE8jYvjB0JQRbAhL9plp2xcCZjdR8y4mUrC2kEyNYSFdOw3Qpx1rIJKbAgMB
        AAGjfDB6MB0GA1UdDgQWBBSVEIG8a5a7YstpCfT26jtMPQoKfDAfBgNVHSMEGDAW
        gBQNZnWx0XNM9H3+IB9wVxEQn6jM+zAJBgNVHRMEAjAAMA4GA1UdDwEB/wQEAwIF
        oDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDQYJKoZIhvcNAQELBQAD
        ggIBAA8NV2MeF0jNXrN/YTNrFGlts8pQXKi8imO16m7+omXV+FWycAJKlHRL1h5q
        FiBhJKz+Y4vIyXSXredh02v28UV7geZ9ufGpyefwyeMtAsOd+UD7l8qHUs1B4mb7
        x/mLmg/4tlFvgZn31JMqWHP9cCWA45Gnq/EZ5A0IBbsaIfp9+FSnXke2z4rl5q/Y
        0WBOUb8XWHL0GOP74Tdf3pxSm/xuwMYnAwP2oIcnV19GLOEybFyAgday2zyvpCU3
        RBNOYx3s7y79NPLUEYOlWnCv3N+WObNRk91TF+KMa8kqq0U4iXjxK62gmlkzGOSO
        JJB47vOt3LNB2BZaUoCrNpBATLuV2Sk0vxER+Bri1HaA4IDmv2c4XJVg7iljaybJ
        BHkqaFSNtk9ScQRumHDGTuc98qZnQFq7ixpRVg8qzAypoTE0hOV2rsPI+oCJw0OW
        4LWY8lkEQgJ+sJ8+UsZqHXy345DeD6GqKv7GZPCwKb5cuQT/ARycZXOqu8abq13i
        JVZVlobGEDdwlgZtGAClfT2TsZOqTTXW3baXLSdwWaDzpUTKCtKabBdFUsfmFU62
        30WRuhU+/doS307aWS/G5Y8K57KwV/Nqw+4svLf0oB9PdwJt15F9bFCf34FmSC+S
        679nrMgMuR2aaClWEzlWssV/OxFLEmUKau+rvt8EH9QguUb4
        -----END CERTIFICATE-----
      # user-2
      - |
        -----BEGIN CERTIFICATE-----
        MIIFADCCAuigAwIBAgIUMnYBXdJWpb7qfxezNbvXoiFzFTAwDQYJKoZIhvcNAQEL
        BQAwfDELMAkGA1UEBhMCVVMxDjAMBgNVBAgMBVN0YXRlMQ0wCwYDVQQHDARDaXR5
        MRUwEwYDVQQKDAxPcmdhbml6YXRpb24xHDAaBgNVBAsME09yZ2FuaXphdGlvbmFs
        IFVuaXQxGTAXBgNVBAMMEE15SW50ZXJtZWRpYXRlQ0EwHhcNMjUxMDAxMTIyNzM0
        WhcNMzUwOTI5MTIyNzM0WjB6MQswCQYDVQQGEwJVUzEOMAwGA1UECAwFU3RhdGUx
        DTALBgNVBAcMBENpdHkxFTATBgNVBAoMDE9yZ2FuaXphdGlvbjEcMBoGA1UECwwT
        T3JnYW5pemF0aW9uYWwgVW5pdDEXMBUGA1UEAwwObXkuZXhhbXBsZS5jb20wggEi
        MA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCDVmRMwCtgoZH6qR32I0iaPCQi
        wgOzXiIUpYXmGgKtTCKy/mDsyW4Ph8DT6Oj+C6WqPIh1Tzloqz3fEpX3lZltZe7J
        Do4Xtc4UdztGC3YIUwj4aYU4sLX8euY4f7hngvnctnnjakK03XK+Dmre179H/lxl
        IS6mSQZGAmnbONtKf7i+iGQhFf0YDnS5pj2tumJ6vIwpemmndlFUme3H743MLt4u
        YiV2W05Zi+Az2OpGeyopr1B4QzOtYowOk5OhBOxPZwdjL/gfZn72zXAsigjLFUQ4
        yfuhniYg9puy9wVephLu40xGHgkjRxp6qmq7ularaWwA8p715fSeoVsxN90NAgMB
        AAGjfDB6MB0GA1UdDgQWBBS9VJyJnB7i390tWeX73hde0O8YkTAfBgNVHSMEGDAW
        gBTAFV1TJ3Lfv3zlwLiykfy/YZ/MujAJBgNVHRMEAjAAMA4GA1UdDwEB/wQEAwIF
        oDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDQYJKoZIhvcNAQELBQAD
        ggIBAGY2t9rAbowmp9TDInJmifS58ELvJbaG31rSSxUWkr28ObzPvsyf6eSeHi/r
        dMKQz8RI1zT1ycRO3FYk+wDpTuX4ybrr7DXP8QNiFjcExVgKxV3/8RybWLxPAx2N
        SKkc/P97mpXzzR5u2OzRFt8lVvKsW0lIjSJLdjoWypoGLjmoTiGSBM1iOgY5g5OE
        ZhyVjbEYMreLpHAMN04cL7z4dL5WkhOhF8Q8MC//WUWt0Blw38G5P45wPn2GRrk2
        GEIXyheuRTbZEfEJkSmLL3lsWYj9Ei+7vCnRAPIpxmBGzy6Tjp3uvjPuohrMDkbb
        esMphjLoRceIzP0Y8xxMX0uSRc1nyvXkxBKrVgVnsP9ErYeSr3F+XP1JbRL8zYai
        stFZ1h/EHmWhhoG6MnuIth5DqaG4q/IWhZqle76Z10YvzPn1/U3mQ1M22J2RBW31
        J7osgIX+57rGC27tHBv5B7kDz70itRCZpyjgVOZ0WrXCMl2ynjqIw+MqDgWsbIoX
        byN8xy0ja3zfMb/4n2QmQzq7vmMwqDMTiHtqPVDTXqy2wDk67roQXT4s+JXmwNEL
        ZCrQuC71GLFzLomutDpjKUlL+9YwIK2f78taQX0EGHhEKE9N9ooUksAc9w8nmm9E
        vOOSWuXGRDTOSPwxwLPLGrZrpv1Qu4+jHK5RbBTXolLIlK/m
        -----END CERTIFICATE-----
    certificateChain:
      - |
        -----BEGIN CERTIFICATE-----
        MIIF5DCCA8ygAwIBAgIUTx5VD4VUJFHynlqkvLDAivd7MpUwDQYJKoZIhvcNAQEL
        BQAwdDELMAkGA1UEBhMCVVMxDjAMBgNVBAgMBVN0YXRlMQ0wCwYDVQQHDARDaXR5
        MRUwEwYDVQQKDAxPcmdhbml6YXRpb24xHDAaBgNVBAsME09yZ2FuaXphdGlvbmFs
        IFVuaXQxETAPBgNVBAMMCE15Um9vdENBMB4XDTI1MTAwMTEyMjUxMVoXDTM1MDky
        OTEyMjUxMVowfDELMAkGA1UEBhMCVVMxDjAMBgNVBAgMBVN0YXRlMQ0wCwYDVQQH
        DARDaXR5MRUwEwYDVQQKDAxPcmdhbml6YXRpb24xHDAaBgNVBAsME09yZ2FuaXph
        dGlvbmFsIFVuaXQxGTAXBgNVBAMMEE15SW50ZXJtZWRpYXRlQ0EwggIiMA0GCSqG
        SIb3DQEBAQUAA4ICDwAwggIKAoICAQCKlCv1GKAfrqr4MqefbPrtPJoUYDkfzz38
        XJcT8UQuiM13sIuIUfszL1QW6J0PrmaU5svWj2MOR9Ci+PmEQzQBLZbfHkpv9F5U
        7p254H4wxcvdHTeMaBL5m79SYBdSUl8Df31oZqvp/5i0sTrYcLRiYh0b85eDEaOe
        Fcy89MzyA6GKpLhemwwWIevKySAls99HObZSovNAM3eYp6yxJNUMeUgGl39pJA1N
        3BqNR2oyy7cHKDZAjbMZW9JgDgF9r349q+H2xNBaubPvMb5KHx9mS1OeIJR1pIF4
        e7bPU/ahgsuyAGYtFa/urb83qNUeIK2groRWnvzORO1yKdeKcW8En8UEd7FzDnLQ
        ra0Ix+NJqaTJ7uGpvBj2QGR6P4+lFM722H9dXmFWuXGhknzCBzteZosYdHRkosq3
        uLChiSgiys9dh36SnVxxPU/9o4vEltT6SmEwIraHqYQZYCaGpn2SIuYpJJVNO0u/
        frU4U6K61mqtJmm+SenyOJYfwQEMGVru+yZeKuuSSjpCXYa325snCnB+n+Ufus/I
        4ASyIQJD3lUUbH4jcHSW3bO5jOS9kS+p274obyEcKAQgoMm7nmhxeSawLM9yhTtk
        JNoMaQK2Mw4Irr1ompyYTlKQe46fVDKooVR5Rvo9Xtwd5+TWs3ok0L8JdNUllXPh
        N7NIRFhXwwIDAQABo2YwZDAdBgNVHQ4EFgQUDWZ1sdFzTPR9/iAfcFcREJ+ozPsw
        HwYDVR0jBBgwFoAUZyHm3zrey3c94B2y4mOyFt/E6ZQwEgYDVR0TAQH/BAgwBgEB
        /wIBADAOBgNVHQ8BAf8EBAMCAYYwDQYJKoZIhvcNAQELBQADggIBAGqvOk5zrl1o
        FjyLim0HGqCsESSGbvQd8GjX0f5qpRDyfgGTDeRFfV+ZegFk/P3kCG8iQwAvplsT
        XvaBZQXc5/FPY8EHWdFOzHlw5iBXZddoQ/zcJwMlZgE/lVHyctjawi/F6jM1QIEU
        0xFkDqP/qYe/e7g8N91afVx9+1It0IAGQx9lYrTQ6D479EuCk3k9jSoll5ssvWPW
        to3s1p+A1W4b7e91XcQbESiNDLyRq9O8gio/25m25X7C2xFif5rkk/dRyIRwJ5EN
        hm3wsZW9oW3Ji/upCV1mC3ARsdXSV656MuBV3EwcW1QTLW3FQ7jvHw3zGPTmx+iN
        44hLKCoUZNrpycItRIafcr/rlMUmE+RLw81ShzLTr0u0occFiUHDAQ+6O9dHvNTh
        LLfGKZKR1O/Z1hCi6iPMqTNHYCwsUXomJucvI4EHo436P4BdaNw5onfxrAGztJin
        knOdqRxbYWXDQ08jGdEATQuprvBzmxcZxhbSKMrp6ahX7ua6oxpXNHuhzRmXjQ7H
        E9eOgRLx45AhPIZwD4bbhIEHDwj76iN14C4Num+rHnTScGZbNlSChk61SeyMby07
        IVP6W3v+veYya77ONVAznpYiuHPazmg5UrvxEg1MUDFCtk5SPCjoD93nmbAwtjIo
        DBFHRc3jQCWx+VmoCSBwdSMwJ3ruUc8e
        -----END CERTIFICATE-----
      - |
        -----BEGIN CERTIFICATE-----
        MIIF2TCCA8GgAwIBAgIUEwkSKZ1raws8aFYsTwebFMMqsNIwDQYJKoZIhvcNAQEL
        BQAwdDELMAkGA1UEBhMCVVMxDjAMBgNVBAgMBVN0YXRlMQ0wCwYDVQQHDARDaXR5
        MRUwEwYDVQQKDAxPcmdhbml6YXRpb24xHDAaBgNVBAsME09yZ2FuaXphdGlvbmFs
        IFVuaXQxETAPBgNVBAMMCE15Um9vdENBMB4XDTI1MTAwMTEyMjUxMFoXDTM1MDky
        OTEyMjUxMFowdDELMAkGA1UEBhMCVVMxDjAMBgNVBAgMBVN0YXRlMQ0wCwYDVQQH
        DARDaXR5MRUwEwYDVQQKDAxPcmdhbml6YXRpb24xHDAaBgNVBAsME09yZ2FuaXph
        dGlvbmFsIFVuaXQxETAPBgNVBAMMCE15Um9vdENBMIICIjANBgkqhkiG9w0BAQEF
        AAOCAg8AMIICCgKCAgEAlUkbXhyTA4YCuaNA8fTfuK76u0EvQWQOHpSj07lR8ddf
        yB1o86ZuLnppfS2ZFVS5WSayFxqzvS2pgTqZ9SIz/sGugQ+of6r0lypx90T+M2DX
        qDCe3Y6VXMA0i2e/Jq1I8BSJ1/NzAEYakKtzOgeGViflQWbc3U14nzzuhqnh1XLU
        eQpEXxh3sfYdLjaSH2ZtcHw8B8jAZrl62zQ/0qpLr5SD4LEE/sHAOHC6f9VgpKgo
        JmFe+un5K5ZVDbwnZjX6I46WfhVI14IFUV747DLD7mShAJuCTS/lBDriQDjFU4Fs
        9ZvC/W6V/0RQhT4fCzWbOwu/HMiwV+aJTDYQFoCkf6gzOtGgCRhUn18cdNCK/jtK
        /QYOxVnNlntWThBXuewL8T8jmLVATKEBjgRdN4hopJJqasHAGWCW68m5gqoT+rNC
        qFg0omE3bKyWJdh4OfnfaMCcN4f9p/1gn3Bl5WVxTxTaeskM13nkU51/Jh2gSV8B
        ykxMGfd9diepxTjdGct4u2aHsZ3kJnyxlXxXceh7evOceP8QSZo9AwX5wvDPwzcY
        up9qCFmWLWxazXaV8QDcyE2foNbLzBw9Y+BIIYnhxrMMQtbX4c/TJ9beMN76chqh
        160m5Z9K/yXBowmBGBsjTtp4GOHQGXjTJyaYRL0byjrtiNxLvvAOjfAZVQmRrJ8C
        AwEAAaNjMGEwHQYDVR0OBBYEFGch5t863st3PeAdsuJjshbfxOmUMB8GA1UdIwQY
        MBaAFGch5t863st3PeAdsuJjshbfxOmUMA8GA1UdEwEB/wQFMAMBAf8wDgYDVR0P
        AQH/BAQDAgGGMA0GCSqGSIb3DQEBCwUAA4ICAQAtf+Q7FITLPC1jpHkHPUSn0i06
        dYjxpUfqbnLdOvu4Os5lKRj9Bjaf/xHIiUfrhMixqTr6ZW7uieBmgKdW5Rb18x7a
        v6zU9imsxCp4GK8ZYBHacgXuuzt6IAc9Bit3l6zWwiIC4u+r3vI37CDQueyKTDF4
        F6R7hjQTT1gIVrD05eLbwIYkuGI+QOldmkbsewDdHLhzWrH7pEKDj3sSEiEudlLe
        EjTgwvoRoHdFZMJ7Rn7b075ssUPbVV48imtfef3/aAun2QSeQiWqfy0NCmIaYb/q
        XWtPObIooRq6YyP7Irc+SVvmva4C/fWPZo5fzRMBisMLunft8xa90zKAFLCHuYmT
        SBtHx95tEVnpAcK37FZRE8Hb0tLHkWITzr0jHaH0l3nogd2879XxAmwdQM2n+BMY
        ck5HCnkA4joWATBeBTKxEa/LKjH9U7QeswtXweiUpaXSRKobEZ15Pb989PRTnlwC
        TejoQefO5cJ4Tz/8/Tr2QSNEM62wqTuZOk3fIwKinLtrQMFR5c8FAzGuLiH8vEPv
        +u2Witz2g5TjOCtgnf3GwdJ7XHh0wWaQf3PH4gqz066sOE8ZVb3kFAipDGsFttwM
        RtyQevXni/SG/SEK8HZ8tvpmQW01wekxqEoIbPWc+Hr2BHLwyH+cArOWRt7uHfnC
        GAYFZvfnP560AbKT7g==
        -----END CERTIFICATE-----
    requireRekorBundle: false
